notifications:
  email: false

language: cpp

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libasound2-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - webkit2gtk-4.0
    - os: osx
      osx_image: xcode9.4
    - os: windows

install: ./setup.sh

script: ./create.sh
